# Generated by Django 3.1.5 on 2021-01-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210119_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=' ', upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
